accounts:
  - name: alice
    coins: ["1000000000zen"]
  - name: bob
    coins: ["500zen"]
validator:
  name: alice
  staked: "100000000zen"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: bob 
  coins: ["50000zen"]
genesis:
  app_state:
    crisis: 
      constant_fee:
        denom: "zen"
    gov: 
      deposit_params: 
          max_deposit_period: "172800s"
          min_deposit: 
            - amount: "10000000"
              denom: "zen"
    staking:
      params:
        bond_denom: "zen"
    mint:
      params:
        mint_denom: "zen"

      