accounts:
  - name: alice
    coins: ["10000000000uzen"]
  - name: bob
    coins: ["5000000000uzen"]
validator:
  name: alice
  staked: "100000000uzen"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: bob 
  coins: ["50000uzen"]
build:
  binary: "zenchaind"
init:
  home: "~/.zenchaind"
genesis:
  app_state:
    crisis: 
      constant_fee:
        denom: "uzen"
    gov: 
      deposit_params: 
          max_deposit_period: "172800s"
          min_deposit: 
            - amount: "100000000"
              denom: "uzen"
    staking:
      params:
        bond_denom: "uzen"
    mint:
      params:
        mint_denom: "uzen"
    token: 
      params: 
        token_tax_rate: "0.400000000000000000"
        issue_token_base_fee: 
          denom: "uzen"
          amount: "1000000000"
        mint_token_fee_ratio: "0.100000000000000000"
    

      