# This is a basic workflow that is manually triggered

name: zenchain

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]
  # push:
  #   # Sequence of patterns matched against refs/tags
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [windows, darwin, linux]
    name: zenchain ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile
        run: |
          go mod download
          go build -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=zenchain \
            -X github.com/cosmos/cosmos-sdk/version.AppName=zenchaind' \
            -o ./build/zenchaind ./cmd/zenchaind

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/zenchaind
          asset_name: zenchaind ${{ matrix.targetos }} ${{ matrix.arch }}
          tag: ${{ github.ref }}

