# This is a basic workflow that is manually triggered

name: zenchain

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]
  # push:
  #   # Sequence of patterns matched against refs/tags
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10


# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [windows, darwin, linux]
    name: zenchain ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile ${{ matrix.arch }} for ${{ matrix.targetos }}
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go mod download
          cd cmd/zenchaind
          go build -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=ZenChain -X github.com/cosmos/cosmos-sdk/version.AppName=zenchaind -X github.com/cosmos/cosmos-sdk/version.Version=1.1.3-2-g7ec7413 -X github.com/cosmos/cosmos-sdk/version.Commit=7ec741347c17989d016ad366c1f8653e5c22f817 ' .
      - uses: actions/upload-artifact@v2
        with:
          name: zenchaind ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/zenchaind/zenchaind